//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unacem.Pgs.Admin.AplicacionCore.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unacem.Pgs.Admin.AplicacionCore.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momentos no es posible registrar la tienda Vuelva a intentarlo mas tarde por favor..
        /// </summary>
        internal static string app_error_CreacionNuevaTiendaFallo {
            get {
                return ResourceManager.GetString("app_error_CreacionNuevaTiendaFallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compra es nula para registrarla..
        /// </summary>
        internal static string app_excepcion_CompraNuloParaRegistrarla {
            get {
                return ResourceManager.GetString("app_excepcion_CompraNuloParaRegistrarla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuota progresol es nula para actualizarla..
        /// </summary>
        internal static string app_excepcion_CuotaProgresolNuloParaActualizarlo {
            get {
                return ResourceManager.GetString("app_excepcion_CuotaProgresolNuloParaActualizarlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor es nulo para registrarla..
        /// </summary>
        internal static string app_excepcion_ProveedorNuloParaActualizarlo {
            get {
                return ResourceManager.GetString("app_excepcion_ProveedorNuloParaActualizarlo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Tienda se registro satisfactoriamente..
        /// </summary>
        internal static string app_informacion_CreacionNuevaTiendaOk {
            get {
                return ResourceManager.GetString("app_informacion_CreacionNuevaTiendaOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Materiales no encontrados para relacionar con proveedor y sus materiales..
        /// </summary>
        internal static string app_validacion_MaterialesNoEncontradosParaRelacionarProveedorMateriales {
            get {
                return ResourceManager.GetString("app_validacion_MaterialesNoEncontradosParaRelacionarProveedorMateriales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progresol asociado a la compra no puede ser uno invalido o nulo..
        /// </summary>
        internal static string app_validacion_ProgresolInvalidoParaGenerarCompra {
            get {
                return ResourceManager.GetString("app_validacion_ProgresolInvalidoParaGenerarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango Tienda Condición Delivery es invalido para actualizar la relacion Tienda..
        /// </summary>
        internal static string app_validacion_TiendaCondicionDelivery {
            get {
                return ResourceManager.GetString("app_validacion_TiendaCondicionDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango Productos destacados es invalido para actualizar la relacion Tienda..
        /// </summary>
        internal static string app_validacion_TiendaSinProductosDestacados {
            get {
                return ResourceManager.GetString("app_validacion_TiendaSinProductosDestacados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango de día de atención es invalido para actualizar la relacion Tienda..
        /// </summary>
        internal static string app_validacion_TiendaSinRangoDiaAtencion {
            get {
                return ResourceManager.GetString("app_validacion_TiendaSinRangoDiaAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango Tiempo entrega es invalido para actualizar la relacion Tienda..
        /// </summary>
        internal static string app_validacion_TiendaSinTiempoEntrega {
            get {
                return ResourceManager.GetString("app_validacion_TiendaSinTiempoEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango Tipo de pago es invalido para actualizar la relacion Tienda..
        /// </summary>
        internal static string app_validacion_TiendaSinTipoDePago {
            get {
                return ResourceManager.GetString("app_validacion_TiendaSinTipoDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo compra asociado a la compra no puede ser uno invalido o nulo..
        /// </summary>
        internal static string app_validacion_TipoCompraInvalidoParaGenerarCompra {
            get {
                return ResourceManager.GetString("app_validacion_TipoCompraInvalidoParaGenerarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La abreviatura del tipo de proveedor no puede ser nulo o vacío..
        /// </summary>
        internal static string dominio_validacion_AbreviaturaTipoProveedorNuloOVacio {
            get {
                return ResourceManager.GetString("dominio_validacion_AbreviaturaTipoProveedorNuloOVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de material en el detalle de la compra no puede ser menor o igual a cero..
        /// </summary>
        internal static string dominio_validacion_CantidadDeCompraDetalleMenorIgualCero {
            get {
                return ResourceManager.GetString("dominio_validacion_CantidadDeCompraDetalleMenorIgualCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de compra del detalle de la compra no puede ser vacío..
        /// </summary>
        internal static string dominio_validacion_CodigoCompraDeCompraDetalleVacio {
            get {
                return ResourceManager.GetString("dominio_validacion_CodigoCompraDeCompraDetalleVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de cuota del progresol no puede ser vacío en los detalles de la cuota..
        /// </summary>
        internal static string dominio_validacion_CodigoCuotaProgresolDeDetalleCuotaProgresolInvalido {
            get {
                return ResourceManager.GetString("dominio_validacion_CodigoCuotaProgresolDeDetalleCuotaProgresolInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de material no puede ser vacío en los detalles de la cuota..
        /// </summary>
        internal static string dominio_validacion_CodigoMaterialDeDetalleCuotaProgresolInvalido {
            get {
                return ResourceManager.GetString("dominio_validacion_CodigoMaterialDeDetalleCuotaProgresolInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de material de la relación proveedor material no puede ser vacío..
        /// </summary>
        internal static string dominio_validacion_CodigoMaterialDeProveedorMaterialInvalido {
            get {
                return ResourceManager.GetString("dominio_validacion_CodigoMaterialDeProveedorMaterialInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El código de proveedor de la relación proveedor material no puede ser vacío..
        /// </summary>
        internal static string dominio_validacion_CodigoProveedorDeProveedorMaterialInvalido {
            get {
                return ResourceManager.GetString("dominio_validacion_CodigoProveedorDeProveedorMaterialInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuota es invalido para actualizar la cuota completada del progresol..
        /// </summary>
        internal static string dominio_validacion_CuotaProgresolNuloActualizaCuotaCompletada {
            get {
                return ResourceManager.GetString("dominio_validacion_CuotaProgresolNuloActualizaCuotaCompletada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción del tipo de compra no puede ser nulo o vacío..
        /// </summary>
        internal static string dominio_validacion_DescripcionTipoCompraNuloOVacio {
            get {
                return ResourceManager.GetString("dominio_validacion_DescripcionTipoCompraNuloOVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción del tipo de proveedor no puede ser nulo o vacío..
        /// </summary>
        internal static string dominio_validacion_DescripcionTipoProveedorNuloOVacio {
            get {
                return ResourceManager.GetString("dominio_validacion_DescripcionTipoProveedorNuloOVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad máxima de días retraso de un registro de compra no puede ser menor o igual a cero..
        /// </summary>
        internal static string dominio_validacion_DiasMaximoParaRegistroCompra {
            get {
                return ResourceManager.GetString("dominio_validacion_DiasMaximoParaRegistroCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha compra asociado a la compra excede a la fecha de hoy, debe registrarse como máximo hasta la fecha actual..
        /// </summary>
        internal static string dominio_validacion_FechaCompraMayorAActualParaGenerarCompra {
            get {
                return ResourceManager.GetString("dominio_validacion_FechaCompraMayorAActualParaGenerarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El limite de la cuota progresol no puede ser menor igual a cero..
        /// </summary>
        internal static string dominio_validacion_LimiteCuotaDeCuotaProgresolNuloOVacio {
            get {
                return ResourceManager.GetString("dominio_validacion_LimiteCuotaDeCuotaProgresolNuloOVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El monto limite cuota por material no puede ser menor o igual a cero en los detalles de la cuota..
        /// </summary>
        internal static string dominio_validacion_LimiteCuotaDeDetalleCuotaProgresolMenorIgualCero {
            get {
                return ResourceManager.GetString("dominio_validacion_LimiteCuotaDeDetalleCuotaProgresolMenorIgualCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha compra asociado a la compra excede el rango de dias permito (7 dias)..
        /// </summary>
        internal static string dominio_validacion_LimiteFechaCompraParaGenerarCompra {
            get {
                return ResourceManager.GetString("dominio_validacion_LimiteFechaCompraParaGenerarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El local del progresol de la cuota progresol no puede ser nulo o vacío..
        /// </summary>
        internal static string dominio_validacion_LocalProgresolDeCuotaProgresolNuloOVacio {
            get {
                return ResourceManager.GetString("dominio_validacion_LocalProgresolDeCuotaProgresolNuloOVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Material asignado a detalle de compra no puede ser nulo o en estado transitorio..
        /// </summary>
        internal static string dominio_validacion_MaterialDeCompraDetalleNulo {
            get {
                return ResourceManager.GetString("dominio_validacion_MaterialDeCompraDetalleNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre o razón social del proveedor no puede ser nulo o vacío..
        /// </summary>
        internal static string dominio_validacion_NombreORazonSocialDeProveedorNuloOVacio {
            get {
                return ResourceManager.GetString("dominio_validacion_NombreORazonSocialDeProveedorNuloOVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El periodo de la cuota progresol no puede ser nulo o vacío..
        /// </summary>
        internal static string dominio_validacion_PeriodoDeCuotaProgresolNuloOVacio {
            get {
                return ResourceManager.GetString("dominio_validacion_PeriodoDeCuotaProgresolNuloOVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progresol asociado a la compra se encuentra en estado inactivo..
        /// </summary>
        internal static string dominio_validacion_ProgresolInactivoParaGenerarCompra {
            get {
                return ResourceManager.GetString("dominio_validacion_ProgresolInactivoParaGenerarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor asignado a compra no puede ser nulo o en estado transitorio..
        /// </summary>
        internal static string dominio_validacion_ProveedorDeCompraNulo {
            get {
                return ResourceManager.GetString("dominio_validacion_ProveedorDeCompraNulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor asociado a la compra se encuentra en estado inactivo..
        /// </summary>
        internal static string dominio_validacion_ProveedorInactivoParaGenerarCompra {
            get {
                return ResourceManager.GetString("dominio_validacion_ProveedorInactivoParaGenerarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo progresol del proveedor no puede ser nulo o vacío..
        /// </summary>
        internal static string dominio_validacion_TipoProgresolDeProveedorNuloOVacio {
            get {
                return ResourceManager.GetString("dominio_validacion_TipoProgresolDeProveedorNuloOVacio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo proveedor asignado a proveedor no puede ser nulo o en estado transitorio..
        /// </summary>
        internal static string dominio_validacion_TipoProveedorDeProveedorNulo {
            get {
                return ResourceManager.GetString("dominio_validacion_TipoProveedorDeProveedorNulo", resourceCulture);
            }
        }
    }
}
