//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unacem.Pgs.Admin.AplicacionCore.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unacem.Pgs.Admin.AplicacionCore.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momento no fue posible traer la información Vuelva a intentarlo mas tarde por favor..
        /// </summary>
        internal static string app_error_Consultar_VideoFallo {
            get {
                return ResourceManager.GetString("app_error_Consultar_VideoFallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momentos no es posible registrar la tienda Vuelva a intentarlo mas tarde por favor..
        /// </summary>
        internal static string app_error_CreacionNuevaTiendaFallo {
            get {
                return ResourceManager.GetString("app_error_CreacionNuevaTiendaFallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momento no fue posible traer la información Vuelva a intentarlo mas tarde por favor..
        /// </summary>
        internal static string app_error_RecuperarLaInformacion {
            get {
                return ResourceManager.GetString("app_error_RecuperarLaInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta información para la creación de la tienda.
        /// </summary>
        internal static string app_excepcion_TiendaNuloParaRegistrarla {
            get {
                return ResourceManager.GetString("app_excepcion_TiendaNuloParaRegistrarla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Tienda se actualizo satisfactoriamente..
        /// </summary>
        internal static string app_informacion_ActualizarTiendaOk {
            get {
                return ResourceManager.GetString("app_informacion_ActualizarTiendaOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Tienda se registro satisfactoriamente..
        /// </summary>
        internal static string app_informacion_CreacionNuevaTiendaOk {
            get {
                return ResourceManager.GetString("app_informacion_CreacionNuevaTiendaOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recupero la información de Tienda satisfactoriamente..
        /// </summary>
        internal static string app_informacion_DatosTiendaOk {
            get {
                return ResourceManager.GetString("app_informacion_DatosTiendaOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se devolvio datos satisfactoriamente..
        /// </summary>
        internal static string app_informacion_RecuperarTiendaOk {
            get {
                return ResourceManager.GetString("app_informacion_RecuperarTiendaOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se devolvio datos satisfactoriamente..
        /// </summary>
        internal static string app_informacion_RecuperarVideosOk {
            get {
                return ResourceManager.GetString("app_informacion_RecuperarVideosOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progresol asociado a la compra no puede ser uno invalido o nulo..
        /// </summary>
        internal static string app_validacion_ProgresolInvalidoParaGenerarCompra {
            get {
                return ResourceManager.GetString("app_validacion_ProgresolInvalidoParaGenerarCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango Tienda Condición Delivery es invalido para actualizar la relacion Tienda..
        /// </summary>
        internal static string app_validacion_TiendaCondicionDelivery {
            get {
                return ResourceManager.GetString("app_validacion_TiendaCondicionDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango Productos destacados es invalido para actualizar la relacion Tienda..
        /// </summary>
        internal static string app_validacion_TiendaSinProductosDestacados {
            get {
                return ResourceManager.GetString("app_validacion_TiendaSinProductosDestacados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango de día de atención es invalido para actualizar la relacion Tienda..
        /// </summary>
        internal static string app_validacion_TiendaSinRangoDiaAtencion {
            get {
                return ResourceManager.GetString("app_validacion_TiendaSinRangoDiaAtencion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango Tiempo entrega es invalido para actualizar la relacion Tienda..
        /// </summary>
        internal static string app_validacion_TiendaSinTiempoEntrega {
            get {
                return ResourceManager.GetString("app_validacion_TiendaSinTiempoEntrega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rango Tipo de pago es invalido para actualizar la relacion Tienda..
        /// </summary>
        internal static string app_validacion_TiendaSinTipoDePago {
            get {
                return ResourceManager.GetString("app_validacion_TiendaSinTipoDePago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tiempo de entrega es invalido para la creación de la Tienda.
        /// </summary>
        internal static string validacion_TiempoEntregaMenorIgualCero {
            get {
                return ResourceManager.GetString("validacion_TiempoEntregaMenorIgualCero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de pago es invalido para la creación de la Tienda.
        /// </summary>
        internal static string validacion_TipoPagoMenorIgualCero {
            get {
                return ResourceManager.GetString("validacion_TipoPagoMenorIgualCero", resourceCulture);
            }
        }
    }
}
