// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unacem.Pgs.Cpra.Infraestructura.Datos;

namespace Unacem.Pgs.Cpra.Infraestructura.Datos.Migrations
{
    [DbContext(typeof(ProgresolContexto))]
    [Migration("20210319062957_InicializaComprasMinorista")]
    partial class InicializaComprasMinorista
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Unacem.Pgs.Cpra.AplicacionCore.Agregados.Compras.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_CATEGORIA_MATERIAL");

                    b.Property<string>("Activo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("FLAG_ACTIVO");

                    b.Property<string>("CodigoCategoriaSap")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("COD_CATEGORIA_SAP");

                    b.Property<string>("NombreCategoria")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DSC_NOMBRE");

                    b.Property<string>("RutaImagen")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DSC_IMAGEN");

                    b.HasKey("Id")
                        .HasName("PK_CATEGORIA_MATERIAL");

                    b.ToTable("PGSTB_CATEGORIA_MATERIAL");
                });

            modelBuilder.Entity("Unacem.Pgs.Cpra.AplicacionCore.Agregados.Compras.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_MATERIAL");

                    b.Property<string>("Activo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("FLAG_ACTIVO");

                    b.Property<Guid>("CodigoCategoria")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_CATEGORIA_MATERIAL");

                    b.Property<string>("CodigoProductoSap")
                        .HasMaxLength(70)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("COD_PRODUCTO_SAP");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FCH_UPD");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FCH_REGISTRO");

                    b.Property<string>("NombreMaterial")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DSC_NOMBRE");

                    b.Property<string>("NombreMaterialParser")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DSC_PRODUCTO_PARSER");

                    b.Property<decimal>("OrdenMaterial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NUM_ORD_MATERIALCEMENTO");

                    b.Property<string>("RutaImagen")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DSC_IMAGEN");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(90)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(90)")
                        .HasColumnName("COD_SKU");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DSC_USUARIO_UPD");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DSC_USUARIO_CREACION");

                    b.HasKey("Id")
                        .HasName("PK_MATERIAL");

                    b.HasIndex("CodigoCategoria");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("PGSTB_MATERIAL");
                });

            modelBuilder.Entity("Unacem.Pgs.Cpra.AplicacionCore.Agregados.Compras.Progresol", b =>
                {
                    b.Property<int>("CodClientepsSap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_CLIENTEPS_SAP")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CelularDueño")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("DSC_CELULAR_DUENO");

                    b.Property<string>("CodigoLocalProgresolSap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COD_PDV");

                    b.Property<string>("CodigoProgresolHijoSap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COD_HIJO");

                    b.Property<string>("CodigoProgresolSap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COD_PADRE");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DSC_DEPARTAMENTO");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DSC_DIRECCION");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DSC_DISTRITO");

                    b.Property<string>("FlagTienda")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_FLAG_TIENDA")
                        .IsFixedLength(true);

                    b.Property<string>("HorarioAtencion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_HORARIO_ATENCION");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Latitud")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_LATITUD");

                    b.Property<string>("LogoTienda")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DSC_LOGO_TIENDA");

                    b.Property<string>("Longitud")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_LONGITUD");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DSC_NOMBRE_COMERCIAL");

                    b.Property<string>("NombreORazonSocialProgresol")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DSC_RAZON_SOCIAL");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DSC_PROVINCIA");

                    b.Property<string>("TipoProgresol")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DSC_TIPO_PROGRESOL");

                    b.HasKey("CodClientepsSap");

                    b.ToTable("PGSTB_TEMP_FUN_CLIENTESPS_SAP");
                });

            modelBuilder.Entity("Unacem.Pgs.Cpra.AplicacionCore.Agregados.Compras.Material", b =>
                {
                    b.HasOne("Unacem.Pgs.Cpra.AplicacionCore.Agregados.Compras.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CodigoCategoria")
                        .HasConstraintName("FK_PGSTB_MATERIAL_PGSTB_CATEGORIA_MATERIAL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });
#pragma warning restore 612, 618
        }
    }
}
