// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unacem.Pgs.Cpra.Infraestructura.Datos;

namespace Unacem.Pgs.Admin.Infraestructura.Datos.Migrations
{
    [DbContext(typeof(ProgresolContexto))]
    [Migration("20211221004420_JIU-NCM_Inicio_EntidadesFiltroMateriales")]
    partial class JIUNCM_Inicio_EntidadesFiltroMateriales
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.Caracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_CARACTERISTICA");

                    b.Property<string>("Activo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("FLAG_ACTIVO");

                    b.Property<string>("CodigoCaracteristicaSap")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("COD_CARACTERISTICA_SAP");

                    b.Property<string>("DescripcionCaracteristica")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DSC_CARACTERISTICA");

                    b.HasKey("Id")
                        .HasName("PK_CARACTERISTICA");

                    b.ToTable("PGSTB_CARACTERISTICA", "dbo");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.CaracteristicaMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_CARACTERISTICA_MATERIAL");

                    b.Property<string>("Activo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("FLAG_ACTIVO");

                    b.Property<Guid>("CodigoCaracteristica")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_CARACTERISTICA");

                    b.Property<Guid>("CodigoMaterial")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_MATERIAL");

                    b.Property<string>("DetalleCaracteristicaMaterial")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DSC_DETALLE_CARACTERISTICA_MATERIAL");

                    b.HasKey("Id")
                        .HasName("PK_CARACTERISTICA_MATERIAL");

                    b.HasIndex("CodigoCaracteristica");

                    b.HasIndex("CodigoMaterial");

                    b.ToTable("PGSTB_CARACTERISTICA_MATERIAL", "dbo");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_MATERIAL");

                    b.Property<string>("Activo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("FLAG_ACTIVO");

                    b.Property<Guid>("CodigoCategoria")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_CATEGORIA_MATERIAL");

                    b.Property<Guid>("CodigoMarca")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_MARCA_MATERIAL");

                    b.Property<string>("CodigoProductoSap")
                        .HasMaxLength(70)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("COD_PRODUCTO_SAP");

                    b.Property<Guid>("CodigoTipo")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_TIPO_MATERIAL");

                    b.Property<Guid>("CodigoUnidadMedida")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_UNIDAD_MEDIDA");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FCH_UPD");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FCH_REGISTRO");

                    b.Property<string>("NombreMaterial")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DSC_NOMBRE");

                    b.Property<string>("NombreMaterialParser")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DSC_PRODUCTO_PARSER");

                    b.Property<decimal>("OrdenMaterial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("NUM_ORD_MATERIALCEMENTO");

                    b.Property<string>("RutaImagen")
                        .HasMaxLength(200)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("DSC_IMAGEN");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(90)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(90)")
                        .HasColumnName("COD_SKU");

                    b.Property<string>("UsuarioActualizacion")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DSC_USUARIO_UPD");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DSC_USUARIO_CREACION");

                    b.HasKey("Id")
                        .HasName("PK_MATERIAL");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("PGSTB_MATERIAL");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.Uso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_USO");

                    b.Property<string>("Activo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("FLAG_ACTIVO");

                    b.Property<string>("CodigoUsoSap")
                        .HasMaxLength(70)
                        .IsUnicode(false)
                        .HasColumnType("varchar(70)")
                        .HasColumnName("COD_USO_SAP");

                    b.Property<string>("DescripcionUso")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DSC_USO");

                    b.HasKey("Id")
                        .HasName("PK_USO");

                    b.ToTable("PGSTB_USO", "dbo");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.UsoMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_USO_MATERIAL");

                    b.Property<string>("Activo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("FLAG_ACTIVO");

                    b.Property<Guid>("CodigoMaterial")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_MATERIAL");

                    b.Property<Guid>("CodigoUso")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("COD_USO");

                    b.Property<string>("DetalleUsoMaterial")
                        .HasMaxLength(300)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DSC_DETALLE_USO_MATERIAL");

                    b.HasKey("Id")
                        .HasName("PK_USO_MATERIAL");

                    b.HasIndex("CodigoMaterial");

                    b.HasIndex("CodigoUso");

                    b.ToTable("PGSTB_USO_MATERIAL", "dbo");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.ProductoDestacados", b =>
                {
                    b.Property<int>("CodProductoDestacado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_PRODUCTO_DESTACADO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Defecto")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_DEFECTO")
                        .IsFixedLength(true);

                    b.Property<string>("DscActivo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_ACTIVO")
                        .IsFixedLength(true);

                    b.Property<string>("DscCategoria")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_CATEGORIA");

                    b.Property<string>("DscNombre")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_NOMBRE");

                    b.Property<string>("DscRuta")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_RUTA");

                    b.Property<DateTime?>("FchActualizacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FCH_ACTUALIZACION");

                    b.Property<DateTime?>("FchCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("FCH_CREACION");

                    b.HasKey("CodProductoDestacado")
                        .HasName("PK_tblProductoDestacado");

                    b.ToTable("PGSTB_PRODUCTO_DESTACADO", "dbo");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.Progresol", b =>
                {
                    b.Property<string>("CodigoLocalProgresolSap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COD_PDV");

                    b.Property<string>("CelularDueño")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("DSC_CELULAR_DUENO");

                    b.Property<string>("CodigoProgresolHijoSap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COD_HIJO");

                    b.Property<string>("CodigoProgresolSap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("COD_PADRE");

                    b.Property<int>("CorrelativoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_CLIENTEPS_SAP")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DSC_DEPARTAMENTO");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DSC_DIRECCION");

                    b.Property<string>("Distrito")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DSC_DISTRITO");

                    b.Property<string>("FlagTienda")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_FLAG_TIENDA")
                        .IsFixedLength(true);

                    b.Property<string>("HorarioAtencion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_HORARIO_ATENCION");

                    b.Property<string>("Latitud")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_LATITUD");

                    b.Property<string>("LogoTienda")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DSC_LOGO_TIENDA");

                    b.Property<string>("Longitud")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_LONGITUD");

                    b.Property<string>("NombreComercial")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DSC_NOMBRE_COMERCIAL");

                    b.Property<string>("NombreORazonSocialProgresol")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DSC_RAZON_SOCIAL");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DSC_PROVINCIA");

                    b.Property<string>("TipoProgresol")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("DSC_TIPO_PROGRESOL");

                    b.HasKey("CodigoLocalProgresolSap")
                        .HasName("PK_TEMP_FUN_CLIENTESPS_SAP_X_LOCAL");

                    b.ToTable("PGSTB_TEMP_FUN_CLIENTESPS_SAP");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.RangoDiaAtencion", b =>
                {
                    b.Property<int>("CodRangoDiaAtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_RANGO_DIA_ATENCION")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Defecto")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_DEFECTO")
                        .IsFixedLength(true);

                    b.Property<string>("DscRangoDia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("DSC_RANGO_DIA");

                    b.HasKey("CodRangoDiaAtencion")
                        .HasName("PK_PGSTB_HORARIO_ATENCION");

                    b.ToTable("PGSTB_RANGO_DIA_ATENCION");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiempoEntrega", b =>
                {
                    b.Property<int>("CodTiempoEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_TIEMPO_ENTREGA")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Defecto")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_DEFECTO")
                        .IsFixedLength(true);

                    b.Property<string>("DscActivo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_ACTIVO")
                        .IsFixedLength(true);

                    b.Property<string>("DscTiempoEntrega")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DSC_TIEMPO_ENTREGA");

                    b.HasKey("CodTiempoEntrega")
                        .HasName("PK_tblTiempoEntrega");

                    b.ToTable("PGSTB_TIEMPO_ENTREGA");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaCondicionDelivery", b =>
                {
                    b.Property<int>("CodTiendaCondDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_COND_DELIVERY")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodCondicionDelivery")
                        .HasColumnType("int")
                        .HasColumnName("COD_CONDICION_DELIVERY");

                    b.Property<int>("CodTiendaProgresol")
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_PROGRESOL");

                    b.Property<string>("DscMontoMin")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("DSC_MONTO_MIN");

                    b.HasKey("CodTiendaCondDelivery")
                        .HasName("PK_tblTienda_CondicionDelivery");

                    b.HasIndex("CodCondicionDelivery");

                    b.HasIndex("CodTiendaProgresol");

                    b.ToTable("PGSTB_TIENDA_CONDICION_DELIVERY");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaHorarioAtencion", b =>
                {
                    b.Property<int>("CodTiendaHorarioAtencion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_HORARIO_ATENCION")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodHoraFin")
                        .HasColumnType("int")
                        .HasColumnName("COD_HORA_FIN");

                    b.Property<int>("CodHoraInicio")
                        .HasColumnType("int")
                        .HasColumnName("COD_HORA_INICIO");

                    b.Property<int>("CodRangoDiaAtencion")
                        .HasColumnType("int")
                        .HasColumnName("COD_RANGO_DIA_ATENCION");

                    b.Property<int>("CodTiendaProgresol")
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_PROGRESOL");

                    b.HasKey("CodTiendaHorarioAtencion")
                        .HasName("PK_PGSTB_TIENDA_HORARIO_ATENCION_1");

                    b.HasIndex("CodRangoDiaAtencion");

                    b.HasIndex("CodTiendaProgresol");

                    b.ToTable("PGSTB_TIENDA_HORARIO_ATENCION");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaProductoDestacados", b =>
                {
                    b.Property<int>("CodTiendaProductoDestacado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_PRODUCTO_DESTACADO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodProductoDestacado")
                        .HasColumnType("int")
                        .HasColumnName("COD_PRODUCTO_DESTACADO");

                    b.Property<int>("CodTiendaProgresol")
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_PROGRESOL");

                    b.HasKey("CodTiendaProductoDestacado");

                    b.HasIndex("CodProductoDestacado");

                    b.HasIndex("CodTiendaProgresol");

                    b.ToTable("PGSTB_TIENDA_PRODUCTO_DESTACADO");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaProgresol", b =>
                {
                    b.Property<int>("CodTiendaProgresol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_PROGRESOL")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_ACTIVO")
                        .IsFixedLength(true);

                    b.Property<string>("Celular")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("DSC_CELULAR");

                    b.Property<string>("CelularOpcional")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("DSC_CELULAR_OPCIONAL");

                    b.Property<string>("CodLocalSap")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("DSC_COD_LOCAL_SAP");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime")
                        .HasColumnName("DSC_FECHA_CREACION");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("datetime")
                        .HasColumnName("DSC_FECHA_MODIFICACION");

                    b.Property<string>("FotoAvatar")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DSC_FOTO_AVATAR");

                    b.Property<string>("HorarioAtencion")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("DSC_HORARIO_ATENCION");

                    b.Property<byte[]>("ImagenAvatar")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("DSC_IMAGEN_AVATAR");

                    b.Property<string>("Negocio")
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("DSC_NEGOCIO");

                    b.Property<string>("NombreComercialCorto")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("DSC_NOMBRE_COMERCIAL_CORTO");

                    b.Property<string>("UsuarioCreacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_USUARIO_CREACION");

                    b.Property<string>("UsuarioModificacion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_USUARIO_MODIFICACION");

                    b.HasKey("CodTiendaProgresol")
                        .HasName("PK_tblTiendaProgresol");

                    b.ToTable("PGSTB_TIENDA_PROGRESOL", "dbo");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaTiempoEntrega", b =>
                {
                    b.Property<int>("CodTiendaTiempoEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_TIEMPO_ENTREGA")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodTiempoEntrega")
                        .HasColumnType("int")
                        .HasColumnName("COD_TIEMPO_ENTREGA");

                    b.Property<int>("CodTiendaProgresol")
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_PROGRESOL");

                    b.HasKey("CodTiendaTiempoEntrega")
                        .HasName("PK_tblTienda_TiempoEntrega");

                    b.HasIndex("CodTiempoEntrega");

                    b.HasIndex("CodTiendaProgresol");

                    b.ToTable("PGSTB_TIENDA_TIEMPO_ENTREGA");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaTipoEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CodTiendaProgresol")
                        .HasColumnType("int");

                    b.Property<int?>("CodTipoEntrega")
                        .HasColumnType("int");

                    b.Property<int>("CodTipoEntregaTienda")
                        .HasColumnType("int");

                    b.Property<Guid?>("TipoEntregaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TipoEntregaId");

                    b.ToTable("TiendaTipoEntrega");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaTipoPago", b =>
                {
                    b.Property<int>("CodTiendaTipoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_TIPO_PAGO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodTiendaProgresol")
                        .HasColumnType("int")
                        .HasColumnName("COD_TIENDA_PROGRESOL");

                    b.Property<int>("CodTipoPago")
                        .HasColumnType("int")
                        .HasColumnName("COD_TIPO_PAGO");

                    b.HasKey("CodTiendaTipoPago")
                        .HasName("PK_tblTienda_TipoPago");

                    b.HasIndex("CodTiendaProgresol");

                    b.HasIndex("CodTipoPago");

                    b.ToTable("PGSTB_TIENDA_TIPO_PAGO");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TipoEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CodTipoEntrega")
                        .HasColumnType("int");

                    b.Property<string>("Defecto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DscRutaLogo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DscTipo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoEntrega");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TipoPago", b =>
                {
                    b.Property<int>("CodTipoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_TIPO_PAGO")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Defecto")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_DEFECTO")
                        .IsFixedLength(true);

                    b.Property<string>("DscActivo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_ACTIVO")
                        .IsFixedLength(true);

                    b.Property<string>("DscRutaLogo")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("DSC_RUTA_LOGO");

                    b.Property<string>("DscTipoPago")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DSC_TIPO_PAGO");

                    b.HasKey("CodTipoPago")
                        .HasName("PK_tblTipoPago");

                    b.ToTable("PGSTB_TIPO_PAGO");
                });

            modelBuilder.Entity("Unacem.Pgs.Cpra.AplicacionCore.Dto.Tienda.CondicionesDelivery", b =>
                {
                    b.Property<int>("CodCondicionDelivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COD_CONDICION_DELIVERY")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Defecto")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_DEFECTO")
                        .IsFixedLength(true);

                    b.Property<string>("DscActivo")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("DSC_ACTIVO")
                        .IsFixedLength(true);

                    b.Property<string>("DscCondicionDelivery")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DSC_CONDICION_DELIVERY");

                    b.HasKey("CodCondicionDelivery")
                        .HasName("PK_tblCondicionesDelivery");

                    b.ToTable("PGSTB_CONDICIONES_DELIVERY");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.CaracteristicaMaterial", b =>
                {
                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.Caracteristica", "Caracteristica")
                        .WithMany("CaracteristicaMateriales")
                        .HasForeignKey("CodigoCaracteristica")
                        .HasConstraintName("FK_PGSTB_CARACTERISTICA_MATERIAL_PGSTB_CARACTERISTICA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.Material", null)
                        .WithMany()
                        .HasForeignKey("CodigoMaterial")
                        .HasConstraintName("FK_PGSTB_CARACTERISTICA_MATERIAL_PGSTB_MATERIAL")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Caracteristica");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.UsoMaterial", b =>
                {
                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.Material", null)
                        .WithMany()
                        .HasForeignKey("CodigoMaterial")
                        .HasConstraintName("FK_PGSTB_USO_MATERIAL_PGSTB_MATERIAL")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.Uso", "Uso")
                        .WithMany("UsoMateriales")
                        .HasForeignKey("CodigoUso")
                        .HasConstraintName("FK_PGSTB_USO_MATERIAL_PGSTB_USO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uso");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaCondicionDelivery", b =>
                {
                    b.HasOne("Unacem.Pgs.Cpra.AplicacionCore.Dto.Tienda.CondicionesDelivery", "CodCondicionDeliveryNavigation")
                        .WithMany("TiendaCondicionDelivery")
                        .HasForeignKey("CodCondicionDelivery")
                        .HasConstraintName("FK_tblTienda_CondicionDelivery_tblCondicionesDelivery")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaProgresol", "CodTiendaProgresolNavigation")
                        .WithMany("TiendaCondicionDelivery")
                        .HasForeignKey("CodTiendaProgresol")
                        .HasConstraintName("FK_tblTienda_CondicionDelivery_tblTiendaProgresol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodCondicionDeliveryNavigation");

                    b.Navigation("CodTiendaProgresolNavigation");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaHorarioAtencion", b =>
                {
                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.RangoDiaAtencion", "CodRangoDiaAtencionNavigation")
                        .WithMany("TiendaHorarioAtencion")
                        .HasForeignKey("CodRangoDiaAtencion")
                        .HasConstraintName("FK__PGSTB_TIE__COD_R__710B0E66")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaProgresol", "CodTiendaProgresolNavigation")
                        .WithMany("TiendaHorarioAtencion")
                        .HasForeignKey("CodTiendaProgresol")
                        .HasConstraintName("FK__PGSTB_TIE__COD_T__71FF329F")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodRangoDiaAtencionNavigation");

                    b.Navigation("CodTiendaProgresolNavigation");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaProductoDestacados", b =>
                {
                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.ProductoDestacados", "CodProductoDestacadoNavigation")
                        .WithMany("TiendaProductosDestacado")
                        .HasForeignKey("CodProductoDestacado")
                        .HasConstraintName("FK_PGSTB_TIENDA_PRODUCTO_DESTACADO_PGSTB_TIENDA_PRODUCTO_DESTACADO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaProgresol", "CodTiendaProgresolNavigation")
                        .WithMany("TiendaProductosDestacados")
                        .HasForeignKey("CodTiendaProgresol")
                        .HasConstraintName("FK_PGSTB_TIENDA_PRODUCTO_DESTACADO_PGSTB_TIENDA_PROGRESOL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodProductoDestacadoNavigation");

                    b.Navigation("CodTiendaProgresolNavigation");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaTiempoEntrega", b =>
                {
                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiempoEntrega", "CodTiempoEntregaNavigation")
                        .WithMany("TiendaTiempoEntrega")
                        .HasForeignKey("CodTiempoEntrega")
                        .HasConstraintName("FK_tblTienda_TiempoEntrega_tblTiempoEntrega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaProgresol", "CodTiendaProgresolNavigation")
                        .WithMany("TiendaTiempoEntrega")
                        .HasForeignKey("CodTiendaProgresol")
                        .HasConstraintName("FK_tblTienda_TiempoEntrega_tblTiendaProgresol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodTiempoEntregaNavigation");

                    b.Navigation("CodTiendaProgresolNavigation");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaTipoEntrega", b =>
                {
                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TipoEntrega", null)
                        .WithMany("TiendaTipoEntrega")
                        .HasForeignKey("TipoEntregaId");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaTipoPago", b =>
                {
                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaProgresol", "CodTiendaProgresolNavigation")
                        .WithMany("TiendaTipoPago")
                        .HasForeignKey("CodTiendaProgresol")
                        .HasConstraintName("FK_tblTienda_TipoPago_tblTiendaProgresol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TipoPago", "CodTipoPagoNavigation")
                        .WithMany("TiendaTipoPago")
                        .HasForeignKey("CodTipoPago")
                        .HasConstraintName("FK_tblTienda_TipoPago_tblTipoPago")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodTiendaProgresolNavigation");

                    b.Navigation("CodTipoPagoNavigation");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.Caracteristica", b =>
                {
                    b.Navigation("CaracteristicaMateriales");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Materiales.Uso", b =>
                {
                    b.Navigation("UsoMateriales");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.ProductoDestacados", b =>
                {
                    b.Navigation("TiendaProductosDestacado");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.RangoDiaAtencion", b =>
                {
                    b.Navigation("TiendaHorarioAtencion");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiempoEntrega", b =>
                {
                    b.Navigation("TiendaTiempoEntrega");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TiendaProgresol", b =>
                {
                    b.Navigation("TiendaCondicionDelivery");

                    b.Navigation("TiendaHorarioAtencion");

                    b.Navigation("TiendaProductosDestacados");

                    b.Navigation("TiendaTiempoEntrega");

                    b.Navigation("TiendaTipoPago");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TipoEntrega", b =>
                {
                    b.Navigation("TiendaTipoEntrega");
                });

            modelBuilder.Entity("Unacem.Pgs.Admin.AplicacionCore.Agregados.Tienda.TipoPago", b =>
                {
                    b.Navigation("TiendaTipoPago");
                });

            modelBuilder.Entity("Unacem.Pgs.Cpra.AplicacionCore.Dto.Tienda.CondicionesDelivery", b =>
                {
                    b.Navigation("TiendaCondicionDelivery");
                });
#pragma warning restore 612, 618
        }
    }
}
