//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unacem.Pgs.Admin.Infraestructura.Datos.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Unacem.Pgs.Admin.Infraestructura.Datos.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recupero información de Progresoles.
        /// </summary>
        internal static string error_App_ConsultaProgresolConResultados {
            get {
                return ResourceManager.GetString("error_App_ConsultaProgresolConResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos la consulta Progresol no devolvio resultado..
        /// </summary>
        internal static string error_App_ConsultaProgresolSinResultados {
            get {
                return ResourceManager.GetString("error_App_ConsultaProgresolSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momentos no se pudo realizar la consulta de tipos de cotizacion. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string error_infraestructura_consultaTiposCotizacionConErrores {
            get {
                return ResourceManager.GetString("error_infraestructura_consultaTiposCotizacionConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momentos no se pudo realizar la consulta de tipos usuario de cotización. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string error_infraestructura_consultaTiposUsuarioCotizacionConErrores {
            get {
                return ResourceManager.GetString("error_infraestructura_consultaTiposUsuarioCotizacionConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recupero información de tipos de cotización..
        /// </summary>
        internal static string informacion_infraestructura_consultarTiposCotizacionConResultados {
            get {
                return ResourceManager.GetString("informacion_infraestructura_consultarTiposCotizacionConResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recupero información de tipos usuario de cotización..
        /// </summary>
        internal static string informacion_infraestructura_consultarTiposUsuarioCotizacionConResultados {
            get {
                return ResourceManager.GetString("informacion_infraestructura_consultarTiposUsuarioCotizacionConResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La consulta no devolvió algún resultado. Cambie los parámetros y vuelva a consultar..
        /// </summary>
        internal static string informacion_infraestructura_consultaTiposCotizacionSinResultados {
            get {
                return ResourceManager.GetString("informacion_infraestructura_consultaTiposCotizacionSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La consulta no devolvió algún resultado. Cambie los parámetros y vuelva a consultar..
        /// </summary>
        internal static string informacion_infraestructura_consultaTiposUsuarioCotizacionSinResultados {
            get {
                return ResourceManager.GetString("informacion_infraestructura_consultaTiposUsuarioCotizacionSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momentos no se pudo realizar la consulta de compras. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_error_ConsultaComprasConErrores {
            get {
                return ResourceManager.GetString("infraDatos_error_ConsultaComprasConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momentos no se pudo realizar la consulta de cuotas progresol por articulos. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_error_ConsultaCuotaProgresolDetalleConErrores {
            get {
                return ResourceManager.GetString("infraDatos_error_ConsultaCuotaProgresolDetalleConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momentos no se pudo realizar la consulta de cuotas progresol resumido. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_error_ConsultaCuotasProgresolConErrores {
            get {
                return ResourceManager.GetString("infraDatos_error_ConsultaCuotasProgresolConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momentos no se pudo realizar la consulta de materiales. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_error_ConsultaMaterialesConErrores {
            get {
                return ResourceManager.GetString("infraDatos_error_ConsultaMaterialesConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momentos no se pudo realizar la consulta de proveedores. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_error_ConsultaProveedoresYMaterialesConErrores {
            get {
                return ResourceManager.GetString("infraDatos_error_ConsultaProveedoresYMaterialesConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos en estos momentos no se pudo realizar la consulta de tipos de compra. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_error_ConsultaTiposCompraConErrores {
            get {
                return ResourceManager.GetString("infraDatos_error_ConsultaTiposCompraConErrores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recupero información para la exportación de las compras..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaComprasConResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaComprasConResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos la consulta de compras no devolvio resultado alguno. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaComprasSinResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaComprasSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recupero información de cuotas progresol por articulos..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaCuotaProgresolDetalleConResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaCuotaProgresolDetalleConResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos la consulta de cuotas progresol por articulos no devolvio resultado alguno. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaCuotaProgresolDetalleSinResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaCuotaProgresolDetalleSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recupero información de cuotas progresol resumido..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaCuotasProgresolConResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaCuotasProgresolConResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos la consulta de cuotas progresol resumido no devolvio resultado alguno. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaCuotasProgresolSinResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaCuotasProgresolSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recupero la información de materiales..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaMaterialesConResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaMaterialesConResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos la consulta de materiales no devolvio resultado alguno. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaMaterialesSinResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaMaterialesSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recupero información de proveedores y sus materiales..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaProveedoresYMaterialesConResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaProveedoresYMaterialesConResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos la consulta de proveedores y sus materiales no devolvio resultado alguno. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaProveedoresYMaterialesSinResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaProveedoresYMaterialesSinResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se recupero información de tipos de compra..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaTiposCompraConResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaTiposCompraConResultados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos la consulta de tipos de compra no devolvio resultado alguno. Vuelva a intentarlo mas tarde..
        /// </summary>
        internal static string infraDatos_informacion_ConsultaTiposCompraSinResultados {
            get {
                return ResourceManager.GetString("infraDatos_informacion_ConsultaTiposCompraSinResultados", resourceCulture);
            }
        }
    }
}
